version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: proyect_image
    container_name: proyect_service
    restart: always
    ports: 
      - 4000:4000
    environment:
      ENV: local
    working_dir: /usr/src
    volumes:
      - ./:/usr/src